- name: Tags in ansible 
  hosts: centos
  become: yes
  tasks:
    - name: Install web server 
      package: 
        name: httpd
        state: present
      tags: web

    - name: Start web server 
      service:
        name: httpd 
        state: started
      tags: web
      
    - name: Install tomcat 
      package:
        name: tomcat 
        state: present
      tags: tomcat

    - name: Start tomcat 
      service:
        name: tomcat 
        state: started
      tags: tomcat