#!/bin/bash

#
# description: Student API init script
# processname: studentapi
# chkconfig: 234 20 80
#

USERNAME={{APPUSER}}
LOC=/home/{{APPUSER}}/api

Start() {
      ps -ef | grep studentapi.war | grep -v grep &>/dev/null
      if [ $? -eq 0 ]; then
         echo "Service Student API already running ..."
         exit 0
      fi
      su - $USERNAME -c "nohup java -jar $LOC/studentapi.war &"
      until netstat -lntp | grep 8090; do
        sleep 10
      done
      }

Stop()  {
      ps -ef | grep studentapi.war | grep -v grep &>/dev/null
      if [ $? -ne 0 ]; then
         echo "Service Student API not running ..."
         exit 0
      fi
      Pid=$(ps -ef | grep studentapi.war | grep -v grep |awk '{print $2}')
      kill -9 $Pid
      }

case $1 in
  start) Start ;;
  stop) Stop ;;
  restart) Stop ; Start ;;
esac